// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace BaseGamePlayTag
{
	//Input Tags
	PALWORLD_BASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PALWORLD_BASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PALWORLD_BASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Run);
	PALWORLD_BASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	PALWORLD_BASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);

	PALWORLD_BASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Run);
	PALWORLD_BASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump);
	PALWORLD_BASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
}
